FROM node:10-alpine

LABEL org.opencontainers.image.source https://github.com/kaans/azure-iot-edge-module-sample

WORKDIR /app/

COPY package*.json ./

RUN npm install --production

COPY app.js ./

USER node

CMD ["node", "app.js"]
