name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        arch: [amd64, arm32v7, arm64v8]

    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v2
      name: Generate production image for ${{ matrix.arch }}
      with:
        context: ./modules/SampleModule
        file: ./modules/SampleModule/Dockerfile.${{ matrix.arch }}
        push: true
        tags: iot_edge_sample_module:latest-${{ matrix.arch }}
