name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        arch: [amd64, arm32v7, arm64v8]
      max-parallel: 1
      fail-fast: true

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      name: Generate production image for ${{ matrix.arch }}
      with:
        context: ./modules/SampleModule
        file: ./modules/SampleModule/Dockerfile.${{ matrix.arch }}
        push: true
        tags: ghcr.io/${{ github.repository }}:latest-${{ matrix.arch }}
