name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        arch: 
          - docker: amd64
            platform: linux/amd64
          - docker: arm32v7
            platform: linux/arm/v7
          - docker: arm64v8
            platform: linux/arm64
      #max-parallel: 1
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      
    - name: Login to Github Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.CONTAINER_REGISTRY_HOSTNAME }}
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - uses: docker/build-push-action@v2
      name: Generate production image for ${{ matrix.arch.docker }}
      with:
        context: ./modules/SampleModule
        file: ./modules/SampleModule/Dockerfile.${{ matrix.arch.docker }}
        push: true
        tags: ghcr.io/${{ github.repository }}:${GITHUB_REF}-${{ matrix.arch.docker }}
        platforms: ${{ matrix.arch.platform }}
